name: Build and push the tagged build to production

on:
  # This tag says that you'll run this workflow only on specific tags
  # In this case, you'll run the workflow only if the tag follows the v* pattern, which includes v1.0.0
  push:
    tags:
      - 'v*'
      
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build_push_image"
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
        # Create a new step that will gather the necessary version information. 
        # You'll use the ::set-output internal command to create this step
        
      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push production image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest,${{secrets.ACR_NAME}}/contoso-website:${{ steps.fetch_version.outputs.TAG }}
          push: true 
